### ISSUE TITLE
[kws_streaming] streaming accuracy calculation 

### ISSUE THREAD

**Issue by AhmedTElthakeb** [google-research/google-research#1482]
@rybakov Hi Oleg, couple queries regarding streaming accuracy calculation 

1) From this [code](https://github.com/google-research/google-research/blob/master/kws_streaming/train/test.py), it seems the streaming accuracy calculation [L169](https://github.com/google-research/google-research/blob/master/kws_streaming/train/test.py#L169) occurs outside the iteration over frames loop [L158](https://github.com/google-research/google-research/blob/master/kws_streaming/train/test.py#L158), although the network outputting new result per frame. Could you please comment on this? Could this be missing potential false alarms?

2) If that is the case, why would streaming accuracy be different compared to non-streaming accuracy given the same model? where is the difference coming from?

3) Lastly, is this streaming inference simulation dependent on the execution engine/hardware?

Thanks!

**Comment by rybakov** [comment]
@AhmedTElthakeb please find comments below:

"From this [code](https://github.com/google-research/google-research/blob/master/kws_streaming/train/test.py), it seems the streaming accuracy calculation [L169](https://github.com/google-research/google-research/blob/master/kws_streaming/train/test.py#L169) occurs outside the iteration over frames loop [L158](https://github.com/google-research/google-research/blob/master/kws_streaming/train/test.py#L158), although the network outputting new result per frame. Could you please comment on this? Could this be missing potential false alarms?"
The goal here is to validate that streaming function has the same accuracy with non streaming one: so I run streaming model in streaming mode and use the last prediction as final one for accuracy computation. This way you can compare non streaming and streaming accuracy. For general evaluation of streaming approach you will need to compute accuracy at every step to measure false alarm in time.

"If that is the case, why would streaming accuracy be different compared to non-streaming accuracy given the same model? where is the difference coming from?"
There will be numerical difference in TF in order of 1e-5, it is due to floating point multiplication as in [line](https://source.corp.google.com/piper///depot/google3/third_party/google_research/google_research/kws_streaming/models/ds_tc_resnet_qat_nbit_test.py;l=53)..

There will be numerical difference when you run it with TFLite because there is numerical difference between TFLite and TF as in [line](https://source.corp.google.com/piper///depot/google3/third_party/google_research/google_research/kws_streaming/models/cnn_test.py;l=162), it is expected around 1e-3 or more.

"Lastly, is this streaming inference simulation dependent on the execution engine/hardware?"
No, it does not depend on execution engine or hardware.

**Comment by AhmedTElthakeb** [comment]
Got it, thanks very much!
