### ISSUE TITLE
Both Bert and Albert Took same time for the inference

### ISSUE THREAD

**Issue by hegebharat** [google-research/google-research#150]
I trained both Bert and Albert using same data(classification task).
 After training
       model size of **Bert** frozen graph() - 420MB
      model size of **Allbert** frozen graph() - 48MB.

When I perform inference, both models are taking same amount of time.
        Time take by **Bert** to classify for singe sentence  - 0.64sec (CPU) -- .0.028sec(K-80 GPU).
        Time take by **AllBert** to classify for singe sentence  - 0.627816sec (CPU) -- .0.023sec(K-80GPU).

I have following questions:
1) Using Albert does not result in good inference time behavior. Only model size is reduced.
Is it expected behavior?

2) If not by how much factor **Albert** is faster than **Bert**(if possible please also provide H/W details.
3) is it not recommend to run the inference on CPU platform? 

Thanks

**Comment by itsucks** [comment]
Hi, it seems you use the albert base model. 
![image](https://user-images.githubusercontent.com/7105813/69701556-28420200-1128-11ea-9102-3a79632714f0.png)
As far as I know, the hidden size and transformer layers of albert are the same with bert base, which two are the main factors to inference time of bert-alike models. The reason of the albert model is much smaller is because it use shared parameters of  transformer layers.
