### ISSUE TITLE
kws_streaming.models.utils_test failure

### ISSUE THREAD

**Issue by Abhipray** [google-research/google-research#241]
I noticed that utils.model_to_tflite() is throwing errors with the GRU model. kws_streaming.models.utils_test fails as well with the following error. I observed this with tf2.1.0 as well as tf2.2.0-dev20200402.

```======================================================================
ERROR: test_model_to_tflite (__main__.UtilsTest)
test_model_to_tflite (__main__.UtilsTest)
TFLite supports stateless graphs.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/abhipray/NeoSensory/git-repos/google-research/kws_streaming/models/utils_test.py", line 85, in test_model_to_tflite
    self.assertTrue(utils.model_to_tflite(self.sess, self.model, self.flags))
  File "/Users/abhipray/NeoSensory/git-repos/google-research/kws_streaming/models/utils.py", line 295, in model_to_tflite
    sess, model_stateless_stream.inputs, model_stateless_stream.outputs)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 792, in from_session
    graph_def = _freeze_graph(sess, input_tensors, output_tensors)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/util.py", line 256, in freeze_graph
    graph_def, input_tensors, output_tensors, config, graph=sess.graph)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/util.py", line 218, in run_graph_optimizations
    return tf_optimizer.OptimizeGraph(config, meta_graph)
  File "/anaconda3/lib/python3.7/site-packages/tensorflow/python/grappler/tf_optimizer.py", line 58, in OptimizeGraph
    graph_id, strip_default_attributes)
ValueError: Failed to import metagraph, check error log for more info.

----------------------------------------------------------------------
Ran 5 tests in 2.938s```

**Comment by rybakov** [comment]
Hi Abhipray,

Please let me know how do you test GRU model and configure GRU testing parameters?

To validate GRU model I run below scripts with env:
Python 3.6.9
tf.__version__ '2.1.0-rc1'

# path where kws_streaming lib is located
KWS_PATH=/tmp/kws_streaming

# path where data2 are unpacked
DATA_PATH=$KWS_PATH/data2

# path where models2 are unpacked
MODELS_PATH=$KWS_PATH/models2

python -m kws_streaming.train.model_train_eval \
--data_url '' \
--data_dir $DATA_PATH/ \
--train_dir $MODELS_PATH/gru/ \
--mel_upper_edge_hertz 7000 \
--how_many_training_steps 10000,10000,10000 \
--learning_rate 0.0005,0.0001,0.00002 \
--window_size_ms 40.0 \
--window_stride_ms 20.0 \
--mel_num_bins 40 \
--dct_num_features 20 \
--resample 0.15 \
--alsologtostderr \
--train 0 \
gru \
--gru_units 400 \
--return_sequences 0 \
--dropout1 0.1 \
--units1 128,256 \
--act1 "'linear','relu'"

It should start prinitng something like:
 tflite test accuracy, non stream model = 94.53% 200 out of 4890
 tflite test accuracy, non stream model = 96.51% 400 out of 4890
 tflite test accuracy, non stream model = 95.67% 600 out of 4890
etc..

After you run above script, please let me know if you see an error again?
Before running above script, I would also try
export CUDA_VISIBLE_DEVICES=-1
to validate that issue is related to running TFLite on CPU or GPU

Thanks,
Oleg.

**Comment by Abhipray** [comment]
Hi Oleg,

I ran `python -m kws_streaming.models.utils_test` as it is and it fails with the error message I shared.  The default script tests dnn model. I got the test to pass by disabling eager execution:
```
if __name__ == '__main__':
    # tf.compat.v1.enable_resource_variables()
    disable_eager_execution()
    tf.test.main()
```
I am using tf2.1 and python 3.7.1 and have no GPUs. 

I ran the same script you shared and see no errors output from running kws_streaming.train.model_train_eval. 

My ultimate goal is to build a streaming GRU model with external state from this library and convert it to tflite, however these errors in convert_to_tflite() show up.

**Comment by rybakov** [comment]
I see, in my tests tfv2 was running with disabled eager mode by default, that is why I did not see this error. Goog catch! Tomorrow a patch (with disabled eager execution) will be submitted for all unit tests.

If you are building a key words detector or sounds detector with GRU model then you can try:

python -m kws_streaming.train.model_train_eval
--data_url ''
--data_dir $DATA_PATH/
--train_dir $MODELS_PATH/gru/
--mel_upper_edge_hertz 7000
--how_many_training_steps 400,400,400
--learning_rate 0.0005,0.0001,0.00002
--window_size_ms 40.0
--window_stride_ms 20.0
--mel_num_bins 40
--dct_num_features 20
--resample 0.15
--alsologtostderr
--train 1
gru
--gru_units 400
--return_sequences 0
--dropout1 0.1
--units1 128,256
--act1 "'linear','relu'"

I reduced number of training iterations to 400,400,400 just for test purpose.
This script will:
1. train GRU model and store it to /tf
2. Convert TF non streaming model to TFLite and store it to /tflite_non_stream
3. Convert TF non streaming model to TF streaming one (with external states) then convert it to TFLite and store it to tflite_stream_state_external
4 It can also can do a TFLite model quantization (if you need to reduce model size and make it faster)

The third step is what you are interested.

/Oleg.

**Comment by rybakov** [comment]
Hi Abhipray,

All unit tests are working.
Also I added more tests to demonstrate how gru model is converted to streaming with TFlite at [testToStreamInferenceModeTFandTFLite(self, model_name='gru'):](https://github.com/google-research/google-research/blob/master/kws_streaming/models/utils_test.py#L263). You can try any other models by changing model_name (some models can not be streamed: 'ds_cnn_stride', 'cnn_stride', 'att_rnn', 'att_mh_rnn').
Please confirm and close the issue.

Best,
Oleg.

**Comment by Abhipray** [comment]
Hi Oleg,

Thank you for taking a look at the unittests. They all pass for me now. Unfortunately, I still get errors when I work with the functions in kws_streaming outside the context of model_train_eval.py. 

Here is a colab showing the error from utils.model_to_tflite(). https://colab.research.google.com/drive/1tIreYkJ5mw1xDbmd7MHMtyRbH26GC4-H

I had some other questions:
- Why not use the tf2.0 tf.lite converter from_keras() method? https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter?version=nightly#from_keras_model
- Why does your tf lite streaming implementation only support external states? Is there something inherently problematic with internal states and tf lite? I made a simple attempt at converting a keras model with internal state and ran into other converter issues like this one https://github.com/tensorflow/tensorflow/issues/37659.

**Comment by rybakov** [comment]
Please find comments below:

_Why not use the tf2.0 tf.lite converter from_keras() method?_ 
It will limit converter to Keras models only. I tried to keep it as generic as possible, so that you can build your model in pure TF or TF.Keras and converter still will work in both cases.

_Why does your tf lite streaming implementation only support external states? Is there something inherently problematic with internal states and tf lite?_
I implemented kws_streaming in a way that you can convert TF to TF streaming with internal states or to TF streaming with internal states. So both streaming modes are supported in this lib.
But TFlite does not support stateful layers now, that is why I test only streaming TFlite with external states (you can build special custom ops with states for TFlite, but I would avoid this path because you will have to customize every stateful layer - it does not scale). TFlite team is working on supporting internal states as general solution and as soon it is enabled, stateful streaming will work out of of the box with this lib.

I tried your colab and it did not work for me (I do not cotroll all env there so it is hard to say why it does not work - it looks like there are some issues with installed TF version).

Please try attached jupyter notebok - it works ok (here all env set up is controlled by yourself):

cd /tmp/kws_streaming
virtualenv --system-site-packages -p python3 ./venv3
source ./venv3/bin/activate
pip install tensorflow==2.1.0-rc1
jupyter notebook

[Untitled.zip](https://github.com/google-research/google-research/files/4459308/Untitled.zip)

**Comment by Abhipray** [comment]
Hi Oleg,

I suspect there might be some other setting on your machine that is different from mine and google colab (https://colab.research.google.com/drive/1tIreYkJ5mw1xDbmd7MHMtyRbH26GC4-H). I followed your steps with virtualenv on my local machine and google colab and get the same error:
 
```WARNING:absl:There is no need to use Stream on time dim with size 1
WARNING:root:FAILED to convert to mode NON_STREAM_INFERENCE, tflite: Fetch argument <tf.Variable 'gru/cell/kernel:0' shape=(20, 96) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("gru/cell/kernel/Read/ReadVariableOp:0", shape=(20, 96), dtype=float32) is not an element of this graph.)```

**Comment by Abhipray** [comment]
Ah I found the issue: the model needs to be instantiated after resetting the graph. Thanks for your help, Oleg!

**Comment by rybakov** [comment]
Good point :)
Just in case here is a working [colab](https://colab.research.google.com/drive/1withkJedDAZtcgTvulVeyLUPnzxpJLnf)

**Comment by Abhipray** [comment]
I found another issue, possible memory-related with the tflite conversion. Here is an example GRU model I am working with:
![image](https://user-images.githubusercontent.com/1261472/78962535-38d89080-7aa9-11ea-8c67-105c7f70a1cf.png)
If input shape is [1,1,20] and the model has three GRU layers with 2 units, the keras model.predict() and tf.lite interpreter outputs are the same. If however, I change the input shape to [1,1,40], I get NaN output from tflite interpreter. If I leave the input shape as [1,1,40] but use 2 layers with 2 nodes, I get an incorrect output (sometimes 0, 1 or NaN) with the tflite interpreter. 

Here is a colab showing the issue: https://colab.research.google.com/drive/1QC73kZgx6yG7af10-RtWIjrWWLFjOcXc

**Comment by rybakov** [comment]
I am not sure about what are you trying to achieve in your colab.
You do not run keras model in streaming mode, so it is not correct to compare tf non streaming with TFLite streaming models.

If you just need to convert your model to TFLite then you should specify 
mode=Modes.NON_STREAM_INFERENCE
as it is done in this [colab](https://colab.research.google.com/drive/1zbnQjkOYfyLfGVal618t0GjlbCXtYuDL#scrollTo=IYeAWXP8incN) - the output should be correct on any feature size and model depth.

Also there is no need to use TimeDistributed wrapper - Dense layer is applied on last dimension in time any way, as it is show in [dense_test](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/dense_test.py)

**Please close this issue and create another one**, because the last one is not related to kws_streaming.models.utils_test failure and can be confusing for other people (it is a good practice not to mix different issues in one ticket).
In the new issue, I will add another colab which explain the difference between non streaming and streaming models in TF and TFLite with gru example.
Thank you for exploring this lib, I appreciate your feedbacks!

**Comment by Abhipray** [comment]
Thanks for the pointers! My problem was that I was not initializing the state inputs to zero before running invoke.

**Comment by rybakov** [comment]
Here is a [colab](https://colab.research.google.com/drive/1wASJnQxpu2bEVOIo4FpgF778edo0wOG8#scrollTo=NcIzzCADklYm) with example of running: 
TF in non streaming
TFlite non streaming
TF streaming with internal state
TF streaming with external state
TFLite with external state

Please have a look at graphs of streaming vs non streaming models in above colab.
It demonstrates a difference between them: streaming with external state has additional inputs for states which you have to intialize 
[inference.zip](https://github.com/google-research/google-research/files/4460251/inference.zip)
and control during inference.
You already figured out your issue :), so hope above colab will be helpful for the next step: running TFLite model in streaming mode.
