### ISSUE TITLE
inference code for video_structure repo

### ISSUE THREAD

**Issue by Berndinio** [google-research/google-research#417]
Is there any inference code for the video_structure repo? 
As far as I can see, there is no code, which uses the keypoints generated from the VRNN (=predicted_keypoints) to generate the predicted image sequence. Instead it uses the keypoints extracted from the input sequence (=observed_keypoints)
The architecture to train the model is like 
image_sequence --> keypoints --> reconstructed_image_sequence-->Recon loss
...................................................|
..................................................V
....................................dynamics_model --> predicted_keypoints -->VRNN losses

reconstructed_images, observed_keypoints, predicted_keypoints is returned from the whole model. Due to this, reconstructed_images is not meaningfull if you want to see generated images from predicted keypoints from the VRNN.

Am I right? Did I get something wrong? As far as I can see, this code is only for training and not inference.
Is there already existing code to generate images from the predicted keypoints/inference? @mjlm

**Comment by mjlm** [comment]
You are right. Since the images reconstructed from `predicted_keypoints` are not used during training, they are not computed in this code. But it is very easy to get them. Simply add
```
  reconstructed_images_pred = keypoints_to_images_net([
      predicted_keypoints,
      input_images[:, 0, Ellipsis],
      observed_keypoints[:, 0, Ellipsis]])
```
below [this line](https://github.com/google-research/google-research/blob/master/video_structure/train.py#L79), and add `reconstructed_images_pred` as one of the model outputs.

And if you already have a trained model, you can dig through the sub-modules of the Keras model object to find the "vision" part of the model (defined [here](https://github.com/google-research/google-research/blob/master/video_structure/vision.py#L105)) and feed it the `predicted_keypoints` to reconstruct the corresponding images.

**Comment by Berndinio** [comment]
Thanks for the fast answer :) Worked!
