### ISSUE TITLE
[POEM] Clarity on row headers of csv file containg 2D

### ISSUE THREAD

**Issue by charishnaidu** [google-research/google-research#439]
Hello!

Thanks for the amazing work and sharing it! 

Through your recent addition of gen_train_tfrecords.py file under tools I am encountering an error regarding csv row length as follows.

'''
File "tools/gen_train_tfrecords.py", line 241, in load_2d_keypoints_and_write_tfrecord_with_3d_keypoints
    raise ValueError('CSV row has length {} but it should have an even'
ValueError: CSV row has length 45 but it should have an evennumber of elements.
'''

From the gen_train_tfrecords.py file (line 22) I am having the row length of 45 itself. Attaching the screen shot for your reference.
![Screenshot from 2020-10-16 17-44-11](https://user-images.githubusercontent.com/38154800/97411758-fb323c80-1900-11eb-9320-f0fe0c5c3df8.png)

I request to help me to correct the csv row length in order to proceed to generate the tfrecod file for training.

Thanks in advance.

**Comment by jenjsun** [comment]
Hello! Thanks for your interest. The training data our model takes in is in pairs, which is why the flag read_csv_pairs is enabled by default. You can create a pair by choosing the same pose from different views, and so the header will be double the size of that from a single pose.

You can also refer to this docstring here: https://github.com/google-research/google-research/blob/master/poem/tools/gen_train_tfrecords.py#L18-L40

**Comment by jenjsun** [comment]
Hello, if this issue is resolved, could you close the issue? Thanks!

**Comment by charishnaidu** [comment]
Thanks for the clarifications provided.
