### ISSUE TITLE
[Scann] Can Scann fit more tf versions?

### ISSUE THREAD

**Issue by SmileTM** [google-research/google-research#473]
Can Scann fit more tf versions?  for example ：tf.2.4, tf.2.4-gpu , and more.
Now， it just fit to tf2.3.0 ， not support tf gpu version.
@sammymax

**Comment by sammymax** [comment]
Because ScaNN interacts with TF at the C++ interface level, maintaining compatibility between TF versions is pretty difficult. The `tf-addons` package has the same issue and [here's what they said about it](https://github.com/tensorflow/addons#c-custom-op-compatibility). We would be more than happy to build ScaNN wheels for TF 2.4 (once it's released, it's still in RC status) but there wouldn't be a good way to distribute the wheels--I don't think pip has a mechanism for "install version A of this package if you have version X of TensorFlow, and install version B of this package if you have version Y of TensorFlow."

Can you clarify more about compatibility with the GPU versions of TF? From what I understand, the GPU version of TF is no longer a separate package, so there really isn't a distinction between GPU and non-GPU TF anymore.

**Comment by SmileTM** [comment]
I think you shuld change pip `requirements.txt`.  
When pip install scann , it will uninstall tf2.x-gpu,  then install tf-2.x .  QAQ. 
@sammymax

**Comment by sammymax** [comment]
What is this tf2.x-gpu package you're referring to? The TensorFlow 2.x package already includes GPU support: https://www.tensorflow.org/install/gpu#pip_package
