### ISSUE TITLE
[SCANN] Compile tensorflow serving with ScaNN Op

### ISSUE THREAD

**Issue by marcinkosztolowicz** [google-research/google-research#566]
Hi
I would like to compile tensorflow serving with ScaNN.

scann: https://github.com/google-research/google-research/tree/master/scann
https://github.com/google-research/google-research/commit/f0721be6ff386e646536f931f8ea2cfe5773b8ff

tensorflow serving: https://github.com/tensorflow/serving
build instruction for custom op: https://www.tensorflow.org/tfx/serving/custom_op

 I have used patches from https://github.com/google-research/google-research/tree/master/scann/tf_serving/patches

**What I did**: 
1. patch original tensorflow serving repo :https://github.com/marcinkosztolowicz/serving/tree/feature/custom-op-scann-2
2. run build tool: `tools/run_in_docker.sh bazel build tensorflow_serving/model_servers:tensorflow_model_server`

**What did I expect?**:
Tensorflow serving binary which is capable of serve model with ScaNN op.

**What i got**:
Compiling errors linked to ScaNN 

**Question**:
@sammymax  What is the correct way to compile tensorflow serving with ScaNN?

**Comment by sammymax** [comment]
I just released Dockerfiles for TF Serving with ScaNN (also see [this bug](https://github.com/tensorflow/recommenders/issues/216)), but if you would still like to compile it yourself, the errors are most likely due to ScaNN using C++17 features or referencing AVX2 intrinsics, so this should work once the compiler is configured correctly. Just note that the TF Serving version should be [this commit](https://github.com/tensorflow/serving/commit/a98d1649061133c589c1a3872aee9ecd774bc52a) or later because previous ones had problems with C++17.

**Comment by marcinkosztolowicz** [comment]
Thank you for your work, docker image will be sufficient for our needs!

**Comment by marcinkosztolowicz** [comment]
It works! Thanks :)

**Comment by xpegenaute** [comment]
Hi!,

first of all thank for your time and effort!. I want to use the tensorfow serving with ScaNN Op and I would like to be able to pass any of these parameters.

```python
tfrs.layers.factorized_top_k.ScaNN(
    query_model: Optional[tf.keras.Model] = None,
    k: int = 10,
    distance_measure: Text = 'dot_product',
    num_leaves: int = 100,
    num_leaves_to_search: int = 10,
    dimensions_per_block: int = 2,
    num_reordering_candidates: Optional[int] = None,
    parallelize_batch_searches: bool = True,
    name: Optional[Text] = None
)
```

 I did'nt see any clear way to do it throught the REST API. Is it possible ?
 
Thanks!,
Xavi
