### ISSUE TITLE
Changing --clip_duration_ms 200 causes error

### ISSUE THREAD

**Issue by StuartIanNaylor** [google-research/google-research#634]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stuart/google-kws/kws_streaming/train/model_train_eval.py", line 366, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/stuart/google-kws/kws_streaming/train/model_train_eval.py", line 147, in main
    train.train(flags)
  File "/home/stuart/google-kws/kws_streaming/train/train.py", line 147, in train
    result = model.train_on_batch(train_fingerprints, train_ground_truth)
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training_v1.py", line 1088, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/keras/backend.py", line 3956, in __call__
    fetched = self._callable_fn(*array_vals,
  File "/home/stuart/google-kws/venv/lib/python3.8/site-packages/tensorflow/python/client/session.py", line 1480, in __call__
    ret = tf_session.TF_SessionRunCallable(self._session._session,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Need minval < maxval, got 0 >= 0
	 [[{{node random_uniform_3}}]]
  (1) Invalid argument: Need minval < maxval, got 0 >= 0
	 [[{{node random_uniform_3}}]]
	 [[Func/training/Adam/gradients/gradients/dropout/cond_grad/StatelessIf/then/_455/input/_1130/_217]]
0 successful operations.
0 derived errors ignored.
```

**Comment by rybakov** [comment]
It is hard to say what is the root cause, without seeing what command did you run and how to reproduce it.
But, I guess this issue can be related to spectrum augmentation: it applies mask on input signal and if signal length is smaller than mask size then it can crash. (with clip_duration_ms=200, you reduced signal length by 5x in comparison to original setting of 1000)
Tow options to fix it:
* Disable spectrum augmentation with "--use_spec_augment 0".
* Change settings of spectrum augmentation by reducing time_mask_max_size and frequency_mask_max_size

**Comment by StuartIanNaylor** [comment]
Many thanks as yeah that is prob it as didn't change the spectrum aug size.
I shall try again.

@rybakov Just another thing that would be so amazing as currently I am turning off split data and creating my own testing, validation & training folders.
I am getting really great noise resilient custom KWS where I am match the amplitude of _back_ground_noise_ to the KW & !KW samples.
This allows me free range of a mix volume of 0-1 and also I can vary the foreground volume without worry of the background being far to predominant with varying inputs.

The end result as said works exceptionally well with noisy environs but because there is no 'volume check' found I am limited to the default 0.3 mix level as higher starts returning too many garbage entries of mainly background in the foreground.

I ended up creating my own split dataset with mixing as in the code struggled to work out how to fit that into the framework, any chance that could be possible as it really does allow more noise resilient and more variance on input volume.

Also with the microcontroller front end are the validation results so bad because for testing its using a wrong MFCC method?
I haven't got round to exporting to microcontroller and using the frontend but wondered in the training part end testing results are due the model created with experimental frontend but testing is via the standard python ops MFCC.

**Comment by rybakov** [comment]
About "noise resilient".
It is hard to comment on it without seeing the code or getting more details about the issues.

About microcontroller front end:
"Also with the microcontroller front end are the validation results so bad because for testing its using a wrong MFCC method?
I haven't got round to exporting to microcontroller and using the frontend but wondered in the training part end testing results are due the model created with experimental frontend but testing is via the standard python ops MFCC."
If you select microcontroller front end, then you have to use it during training and inference, because it is not numerically compatible with tf MFCC.
