### ISSUE TITLE
Cannot run Inference from colab notebook 02_inference.ipynb

### ISSUE THREAD

**Issue by vishalkevat007** [google-research/google-research#783]
The project is KWS-streaming.

The training ran successfully. In Inference for "SVDF Model", the colab notebook provided, 02_inference.ipynb, There in no output while running the cell 

(convert model to inference mode with batch one)
inference_batch_size = 1
tf.keras.backend.set_learning_phase(0)
flags.batch_size = inference_batch_size  # set batch size
model_non_stream = utils.to_streaming_inference(model_non_stream_batch, flags, Modes.NON_STREAM_INFERENCE)

The cell has been running for too long on the last code line
i.e **model_non_stream = utils.to_streaming_inference(model_non_stream_batch, flags, Modes.NON_STREAM_INFERENCE)**
and there was no output nor any error, seems it is in a loop.

Please help!

**Comment by omerc1** [comment]
Try to update tf-nightly package. 
I had a similar problem and it helped.

**Comment by rybakov** [comment]
@vishalkevat007 all dependencies are described in [experiment](https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_12_labels.md#install-tensorflow-with-deps)

You should install:
```
pip install --upgrade pip
pip install tf_nightly
pip install tensorflow_addons
pip install tensorflow_model_optimization

# install libs:
pip install pydot
pip install graphviz
pip install numpy
pip install absl-py
```

I run colab using jupyter notebook
So I also install it, by running:
```
pip install notebook
```
Then start a notebook by running:
```
jupyter notebook
```
After that load colab from [folder](https://github.com/google-research/google-research/tree/master/kws_streaming/colab) and run it step by step. This way there is no need to install anything in colab.


You can also install dependencies directly in colab by executing:
```
!pip install tf_nightly
```
But I prefer to avoid it, so that you don run this installation in every colab.
More details about this option are described in [link](https://stackoverflow.com/questions/54223282/installing-tf-nightly-gpu-2-0-preview-on-google-colab)

**Comment by vishalkevat007** [comment]
@rybakov Thank you, it worked!
